name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *" 
  workflow_dispatch:
  push:
    branches:
    - main

permissions: 
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 
      
      - uses: Platane/snk@v3
        with:
          github_user_name: TraMi2209
          # Tùy chỉnh màu sắc cực Pro tại đây
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg?color_snake=#00FFFF&color_dots=#161b22,#1b4b82,#1f6fad,#2792d6,#FFFFFF
            
      - uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
